### ISSUE TITLE
Sticky header overlapping the target anchor

### ISSUE THREAD

**Issue by anthonydillon** [canonical/charmhub.io#1106]
I found a few places the sticky header is broken:
- https://charmhub.io/grafana-k8s/configure#port
- https://charmhub.io/grafana-k8s/libraries/grafana_dashboard#grafanadashboardschanged

**Comment by anasereijo** [comment]
@anthonydillon I can't replicate this issue – can you please confirm if it's still happening? If so, some screenshots would be helpful. thanks!

**Comment by steverydz** [comment]
This was fixed in a previous issue.
