### ISSUE TITLE
Bundle icons not showing in filtered list of bundles

### ISSUE THREAD

**Issue by knotuteye** [canonical/charmhub.io#1370]
To reproduce, navigate to: [https://charmhub.io/?base=all&type=bundle](https://charmhub.io/?base=all&type=bundle)

OR

1. Navigate to charmhub.io
2. FIlter by Bundles
3. Refresh

<img width="1190" alt="Screenshot 2022-06-30 at 9 19 13 AM" src="https://user-images.githubusercontent.com/36668279/176641130-fa81a79b-31bf-41ff-a5e9-bfc45f07d333.png">

**Comment by Lukewh** [comment]
Fixed as part of the bundle visibility work :+1:
