### ISSUE TITLE
Anchored link doesn't quite work with a new tab

### ISSUE THREAD

**Issue by nobuto-m** [canonical/charmhub.io#1396]
Charmhub has an anchored link/id to each charm config option. e.g.,
https://charmhub.io/ceph-osd/configure#ephemeral-unmount

However, the rendering is different between when the anchored link is clicked after opening the page and when the anchored link is opened directly as a new tab.

[`ephemeral-unmount` on the left pane was clicked after opening the charm page]

![Screenshot from 2022-09-01 12-03-32](https://user-images.githubusercontent.com/4356209/187823518-a67d09cc-4793-4dfe-be6c-2c95dc7d5cd6.png)

^^^ `ephemeral-unmount` on the left pane is highlighted and the config title in the right pane is visible.

[the anchored link is directly opened as a new tab]
![Screenshot from 2022-09-01 12-02-40](https://user-images.githubusercontent.com/4356209/187823679-421b9b97-4c4e-4ade-b06b-0c5a3ec27e01.png)

^^^ `ephemeral-unmount` on the left pane is not highlighted but the first option `aa-profile-mode` is highlighted. Also the config title in the right pane `ephemeral-unmount` is not visible.

Confirmed with both Chromium and Firefox on Ubuntu.

**Comment by steverydz** [comment]
Thanks for raising this issue. We'll look into this.

**Comment by steverydz** [comment]
Hi @nobuto-m. A fix for this has been deployed.

**Comment by nobuto-m** [comment]
Hmm, it actually has a trickier behavior now.

[new tab]
![image](https://user-images.githubusercontent.com/4356209/187887550-b127c351-188c-4afa-a426-680ddaad0c78.png)

^^^ left pane not highlighted, right pane has some extra space on the config title.

[in page clicking]
![image](https://user-images.githubusercontent.com/4356209/187887814-b4ba468d-acec-4c07-854c-c7bd89e77f43.png)

^^^ works as expected

[in page, clicking the config name again (twice in total)]
![image](https://user-images.githubusercontent.com/4356209/187887686-1b12064a-f2c9-431b-af01-6e1788070d88.png)

^^^ the config title gets hidden by the scrolling position.

**Comment by nobuto-m** [comment]
I'm not sure if the new changes have been provisioned or not. But as of right now, the page has a mixed behavior of the initial set of issues:
https://github.com/canonical/charmhub.io/issues/1396#issue-1358183452
and the second set of issues:
https://github.com/canonical/charmhub.io/issues/1396#issuecomment-1234049368

**Comment by steverydz** [comment]
Hi @nobuto-m. The changes were put live towards the end of yesterday. It's possible that you might need to clear your cache as we can produce the problem since the changes have gone live.

**Comment by nobuto-m** [comment]
Can you please revisit this? It still has some mixed behaviors to me.

Here is a recording with Chromium v105.

https://user-images.githubusercontent.com/4356209/188799115-d4dad8db-7c54-4226-80e9-fc5e83456e0e.mp4

Also, it looks like it behaves trickier with Firefox.
