### ISSUE TITLE
Update links to some charms on homepage

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmhub.io#1407]
Please update some links to charms currently listed on the homepage:

* Discourse should link to https://charmhub.io/discourse-k8s. Please also remove https://charmhub.io/discourse-charmers-discourse-k8s from search results on charmhub (for "discourse", for instance).
* Jenkins-Agent should link to https://charmhub.io/jenkins-agent-k8s. Please also remove https://charmhub.io/jenkins-ci-charmers-jenkins-agent from search results on charmhub (for "jenkins", for instance).

Thanks, Tom

**Comment by mthaddon** [comment]
Have also filed this on discourse - https://discourse.charmhub.io/t/some-updates-to-charmhub-homepage-links/7417.

**Comment by arturo-seijas** [comment]
Hi! Any news about this @Roadmaster ?

**Comment by Lukewh** [comment]
The PR above makes the changes to the homepage items, but it will not remove the previous charms from search results.

**Comment by arturo-seijas** [comment]
> The PR above makes the changes to the homepage items, but it will not remove the previous charms from search results.

Is there any action needed from our side for that?

**Comment by Roadmaster** [comment]
Hi, I've unlisted the old charms.

**Comment by arturo-seijas** [comment]
> Hi, I've unlisted the old charms.

Thank you @Roadmaster I see the changes are already reflected. I think you can close the ticket
