### ISSUE TITLE
Can't find the ubuntu-advantage charm

### ISSUE THREAD

**Issue by axinojolais** [canonical/charmhub.io#1412]
Hi,

The ubuntu-advantage charm exists : https://charmhub.io/ubuntu-advantage

Yet it doesn't come up in search : 
https://charmhub.io/?q=ubuntu
https://charmhub.io/?q=advantage
https://charmhub.io/?q=ubuntu-advantage

Is there a reason for that ? UA is an official Ubuntu product, so it seems strange.

Thanks

**Comment by mthaddon** [comment]
To do this we need to create a post on Discourse in the charm requests category (https://discourse.charmhub.io/c/charmhub-requests/46) asking for the charm to be searchable.

**Comment by Lukewh** [comment]
Is there an action for the charmhub.io website maintainers for this? Is it being tracked somewhere else?

**Comment by mthaddon** [comment]
I think it's fine to close out this issue. The question of the charm name and ownership (given UA has been renamed to Pro) is still under discussion, and we can address the searchability of the charm as part of that.

**Comment by Lukewh** [comment]
Thanks @mthaddon
