### ISSUE TITLE
Add `copy to clipboard` button

### ISSUE THREAD

**Issue by sudeephb** [canonical/charmhub.io#1415]
It would be handy to have a `copy to clipboard` button beside the `juju deploy <charm>` command in the charmhub UI(to copy the deploy command).

**Comment by anthonydillon** [comment]
We understand that this is a commonly available function on sites like this. But we deem it risky to paste copied commands programmatic into production environments. Therefore, we have opted to omit this functionality and rely on direct copy and paste of the text or typing of the commands.
