### ISSUE TITLE
Charmhub shows the architecture / series supported by the highest revision

### ISSUE THREAD

**Issue by hloeung** [canonical/charmhub.io#1416]
Hi,

We're in the process of migrating our charms to use Launchpad to build, this is to address the various Python depencenies per https://github.com/juju/charm-tools/issues/647.

Unfortunately, charmhub.io shows the supported series and architecture of the highest/latest revision, see autocert for example here https://charmhub.io/autocert-charmers-autocert

It shows as 22.04 on arm64 and nothing else. But there are multiple revisions each supporting a specific series on a specific architecture:
```
$ for arch in amd64 arm64 ppc64el s390x; do for series in xenial bionic focal jammy; do echo "$arch | $series"; juju info autocert-charmers-autocert --series "$series" --arch "$arch" | grep '^  latest/edge'; done; done
amd64 | xenial
  latest/edge:       1729e13  2022-10-19  (79)  5MB
amd64 | bionic
  latest/edge:       1729e13  2022-10-19  (80)  5MB
amd64 | focal
  latest/edge:       1729e13  2022-10-19  (81)  6MB
amd64 | jammy
  latest/edge:       1729e13  2022-10-19  (82)  10MB
arm64 | xenial
  latest/edge:       1729e13  2022-10-19  (92)  5MB
arm64 | bionic
  latest/edge:       1729e13  2022-10-19  (84)  5MB
arm64 | focal
  latest/edge:       1729e13  2022-10-19  (90)  6MB
arm64 | jammy
  latest/edge:       1729e13  2022-10-19  (94)  10MB
ppc64el | xenial
  latest/edge:       1729e13  2022-10-19  (85)  5MB
ppc64el | bionic
  latest/edge:       1729e13  2022-10-19  (86)  5MB
ppc64el | focal
  latest/edge:       1729e13  2022-10-19  (88)  6MB
ppc64el | jammy
  latest/edge:       1729e13  2022-10-19  (91)  10MB
s390x | xenial
  latest/edge:       1729e13  2022-10-19  (83)  5MB
s390x | bionic
  latest/edge:       1729e13  2022-10-19  (89)  5MB
s390x | focal
  latest/edge:       1729e13  2022-10-19  (87)  6MB
s390x | jammy
  latest/edge:       1729e13  2022-10-19  (93)  10MB
```

I'm not sure how charmhub.io will handle this, perhaps gather and group by the commit? e.g. 1729e13 in the example above?

**Comment by Lukewh** [comment]
I'm not 100% sure what you mean. But if you click the dropdown to show the channel map do you not see the supported series and architectures for each channel?
If you click on one of those channels the top right of the header should also update.

![image](https://user-images.githubusercontent.com/479384/203800849-8effac86-e47e-4531-8831-3eb7a55511ff.png)

**Comment by hloeung** [comment]
We're moving to per-series & per-architecture charms per https://github.com/juju/charm-tools/issues/647#issuecomment-1281832894 and in particular, https://discourse.charmhub.io/t/charmcraft-bases-provider-support/4713.

So each revision is for a specific series plus architecture. In the above, `110` is built for and would only be guaranteed to work on `Jammy` (`Ubuntu 22.04` per the above) and `arm64`, not shown above.

The above charmhub UI also doesn't show the specific revisions that will work for the other series + architectures. The only way currently to see this is as follows:
```
$ for series in jammy focal bionic xenial; do for arch in amd64 arm64 ppc64el s390x; do echo "$series / $arch:"; juju info autocert-charmers-autocert --channel latest/stable --series $series --arch $arch | grep '^  latest/stable:'; done; done
jammy / amd64:
  latest/stable:     8a21f91  2022-10-21  (98)  10MB
jammy / arm64:
  latest/stable:     8a21f91  2022-10-21  (110)  10MB
jammy / ppc64el:
  latest/stable:     8a21f91  2022-10-21  (106)  10MB
jammy / s390x:
  latest/stable:     8a21f91  2022-10-21  (109)  10MB
focal / amd64:
  latest/stable:     8a21f91  2022-10-21  (97)  6MB
focal / arm64:
  latest/stable:     8a21f91  2022-10-21  (108)  6MB
focal / ppc64el:
  latest/stable:     8a21f91  2022-10-21  (103)  6MB
focal / s390x:
  latest/stable:     8a21f91  2022-10-21  (105)  6MB
bionic / amd64:
  latest/stable:     8a21f91  2022-10-21  (95)  5MB
bionic / arm64:
  latest/stable:     8a21f91  2022-10-21  (100)  5MB
bionic / ppc64el:
  latest/stable:     8a21f91  2022-10-21  (104)  5MB
bionic / s390x:
  latest/stable:     8a21f91  2022-10-21  (101)  5MB
xenial / amd64:
  latest/stable:     8a21f91  2022-10-21  (96)  5MB
xenial / arm64:
  latest/stable:     8a21f91  2022-10-21  (107)  5MB
xenial / ppc64el:
  latest/stable:     8a21f91  2022-10-21  (99)  5MB
xenial / s390x:
  latest/stable:     8a21f91  2022-10-21  (102)  5MB
```

They're all the same charm commit, `8a21f91`.

**Comment by hloeung** [comment]
I just noticed that there is a drop down for architecture so maybe these can be moved into that. But right now, there's a bug there too that it only shows amd64, see attached.
![5UkaweuU0Q](https://user-images.githubusercontent.com/95021/203857925-da928ef1-bf9e-447b-bf2b-709b8bf416fa.png)

**Comment by Lukewh** [comment]
I see, we'll look into fixing this. Also, that does seem to be a bug with the current switcher, we'll take a look at that too :)!.
