### ISSUE TITLE
Collapsible navigation levels for Observability Stack docs

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmhub.io#1418]
@0x12b likes the collapsible side bar on this page https://juju.is/docs/sdk and would like the same for this page: https://charmhub.io/topics/canonical-observability-stack . Would that be possible? When? Thanks in advance!

**Comment by bartaz** [comment]
Thanks @tmihoc, Marketplace devs should be able to pick it up from here.

Reusing the template (and accompanying JS) from juju.is should do the trick (possibly navigation levels needs adjusting in the config if needed). It's documented in more detail in discourse: https://discourse.canonical.com/t/creating-discourse-based-documentation-pages/159

If there are any issues with that I should be able to help.
