### ISSUE TITLE
Collapsible navigation levels for Charmed Kubeflow docs

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmhub.io#1421]
@andreeamun  likes the collapsible side bar on this page https://juju.is/docs/olm and would like the same for this page: https://charmed-kubeflow.io/docs . Would that be possible? When? Thanks in advance!

@bartaz pinging you because you recently helped with https://github.com/canonical/charmhub.io/issues/1418 and this is similar.

**Comment by Lukewh** [comment]
I think this should be filed on https://github.com/canonical/charmed-kubeflow.io/issues instead?

**Comment by tmihoc** [comment]
@Lukewh thanks, filed it there now: https://github.com/canonical/charmed-kubeflow.io/issues/135
