### ISSUE TITLE
Juju fails to pull image from charmcraft

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charmhub.io#1470]
Hi!,

I'm not sure if I should be filing this ticket here, it might require coordination with the Juju team.

We've recently experienced an issue while deploying a charm in our k8s cluster, specifically postgresql-k8s from stable charnnel, revision 20). Docker wasn't able to pull the image due to failed authentication:
```
  Warning  Failed                  23m (x4 over 25m)  kubelet                  Failed to pull image "registry.jujucharms.com/charm/kotcfrohea62xreenq1q75n1lyspke0qkurhk/postgresql-image@sha256:8a72e1152d4a01cd9f4697093d3815af4a48bb68731b2b292e3cb18163d8feff": rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.jujucharms.com/charm/kotcfrohea62xreenq1q75n1lyspke0qkurhk/postgresql-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  ```

Given that this charm is publicly available, I wouldn't expect any authentication to be performed, hence, I suggest removing it if possible.

Thank you!

**Comment by mthaddon** [comment]
This has been filed as https://bugs.launchpad.net/juju/+bug/2011710, so this can be closed out.
