### ISSUE TITLE
"Platforms" widget in the charm page header is broken

### ISSUE THREAD

**Issue by grobbie** [canonical/charmhub.io#1481]
The Platforms widget shows the wrong platforms (this charm channel and track only supports focal) and it shows them 3x over...
![image](https://user-images.githubusercontent.com/3254480/216356324-f5ecb0ab-c56a-46e2-bf00-221e14e12eab.png)
The widget should only show the supported platforms of the currently selected channel, track and revision of the charm.
Thanks

**Comment by steverydz** [comment]
Thanks for the bug report. This should be fixed now.
