### ISSUE TITLE
Libraries tab only shows `latest/stable` channel information.

### ISSUE THREAD

**Issue by zmraul** [canonical/charmhub.io#1486]
When looking at the `Libraries` tab in a charm page, you can only browse the latest channel. If the edge version of a charm doesn't use a lib anymore, or something is deprecated, there is no clear way to show that on charmhub.

Is this intended?

**Comment by Lukewh** [comment]
This should be fixed now @zmraul, if not can you provide a link to the charm you've seen this issue on so we can debug further, thanks :).
