### ISSUE TITLE
Broken links on charmhub's login landing page

### ISSUE THREAD

**Issue by gboutry** [canonical/charmhub.io#1502]
These two links lead to a 404 error. They are among the first links appearing after logging in Charmhub.

https://github.com/canonical/charmhub.io/blob/668bd327e96a47cbd0c4db2391e77f38ef9e5972/templates/publisher/list.html#L18

https://github.com/canonical/charmhub.io/blob/668bd327e96a47cbd0c4db2391e77f38ef9e5972/templates/publisher/list.html#L230

**Comment by Lukewh** [comment]
Thanks for the report @gboutry we're currently updating our documentation and we missed these links, I'll update them now :)
