### ISSUE TITLE
Generate a charm's landing page from the `docs` entry (if present) rather than the README

### ISSUE THREAD

**Issue by sed-i** [canonical/charmhub.io#1521]
From a documentation perspective, currently charmhub does this:
- generates the landing page from the readme
- generates the doc tree sidebar from the `| Level | Path | Navlink |` navtable in the `docs` page
- ignores the rest of the content of the `docs` page on discourse ([example](https://discourse.charmhub.io/t/alertmanager-k8s-docs-index/5788))

![image](https://user-images.githubusercontent.com/82407168/221003161-25f8d9f5-c6b7-49ec-bc53-15de2db05af7.png)

Example: alertmanager - [ch](https://charmhub.io/alertmanager-k8s?channel=edge) - [docs entry](https://discourse.charmhub.io/t/alertmanager-k8s-docs-index/5788).

It would probably be more advantageous if instead charmhub generated the landing page from the `docs` page: we would be freed from to the github-charmhub dual-purpose README.

![image](https://user-images.githubusercontent.com/82407168/221004467-ad3ec27f-d355-46b5-8be0-2a1e258e4160.png)

cc: @tmihoc @mthaddon @Lukewh

**Comment by Lukewh** [comment]
It has, thanks for the ping @tmihoc and the suggestion @sed-i :)
