### ISSUE TITLE
The mermaid diagram is not shown on Description (the content from Discourse)

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charmhub.io#1525]
Hi,

Please check mysql-router on charmhub.io: https://charmhub.io/mysql-router?channel=dpe/edge
and on GitHub: https://github.com/canonical/mysql-router-operator/blob/main/README.md

As you can see the basic mermaid diagram is not processed on charmhub.io and shown as a plain text: `flowchart TD...`

![Screenshot from 2023-02-27 22-51-05](https://user-images.githubusercontent.com/1928266/221694206-130c0915-9217-46fc-ac47-3bcd542ee632.png)

It looks like https://warthogs.atlassian.net/browse/WD-665 was a subtask for develop mermaid support.
Is it a not-yet implemented feature or a bug? Thank you!

P.S. we would like to publish more [complex](https://github.com/canonical/pgbouncer-k8s-operator/blob/main/documentation/reference/charm.md) diagrams, but without charmhub.io support mermaid is a risky choice.

**Comment by taurus-forever** [comment]
Hint: if you wish to publish mermaid on charmhub: publish screenshots with links to GitHub, e.g. https://charmhub.io/postgresql-k8s/docs/e-charm?channel=14/stable

**Comment by Lukewh** [comment]
I believe this is no longer relevant since we made [this](https://discourse.charmhub.io/t/changes-to-charmhub-io-pages/9366) change. Closing, but please reopen if you think it's still relevant :).

**Comment by taurus-forever** [comment]
Dear @Lukewh , it is still relevant for Data Platform team.

Please see the following examples:
https://charmhub.io/mysql-k8s/docs/e-flowcharts
https://charmhub.io/postgresql-k8s/docs/e-charm
https://charmhub.io/postgresql-k8s/docs/e-peers
https://charmhub.io/postgresql-k8s/docs/e-backups

As you can see we are actively using mermaid diagrams to describe the internal logic of our charms.
Unfortunately it produces issues for us on Discourse->GitHub sync. We have to manually restore mermaid blocks in bot PRs, example:
https://github.com/canonical/mysql-k8s-operator/pull/222/commits/4a5aeae3b0cf4f2897ab81385d0a8256696e1164

We really looking forward to add mermaid support for charmhub.io ([as Discourse supports mermaid nowadays](https://meta.discourse.org/t/discourse-mermaid/218242)). Please reopen this issue. Thank you!

**Comment by Lukewh** [comment]
Aha, I see. I'll reopen and rename this issue to relate to discourse rendering, not GitHub README renderin :+1:

**Comment by Lukewh** [comment]
@taurus-forever this is now live, and you can see the resulting diagram on https://charmhub.io/mysql-k8s/docs/e-flowcharts :).

**Comment by taurus-forever** [comment]
> ... this is now live ...

You are my HERO! Thank YOU!!!
P.S. applied the change to https://charmhub.io/mysql-k8s/docs/e-flowcharts (all other pages will follow).
P.P.S. It implies our life A LOT. THANK YOU!!!

**Comment by taurus-forever** [comment]
@Lukewh there is a small bug (if page has 2+ diagrams): https://charmhub.io/postgresql-k8s/docs/e-charm
Should I report it as a separate issue?

**Comment by Lukewh** [comment]
> @Lukewh there is a small bug (if page has 2+ diagrams): [charmhub.io/postgresql-k8s/docs/e-charm](https://charmhub.io/postgresql-k8s/docs/e-charm) Should I report it as a separate issue?

Please do! I'll take a look anyway, but good to track it separately :)

**Comment by Lukewh** [comment]
@taurus-forever never mind,  already merged: https://github.com/canonical/charmhub.io/pull/1586 :)

**Comment by taurus-forever** [comment]
> @taurus-forever never mind, already merged: #1586 :)

The fix confirmed, thank you one more time!
