### ISSUE TITLE
Charmhub Integrations tab reverse use for provides/consumes

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charmhub.io#1531]
Hi,

It looks like Integrations tab improperly shows `provides/consumes`.

E.g. see: https://charmhub.io/mysql-k8s/integrations
"Percona Cluster consumes mysql" (while it provides it).
"Charmed MongoDB K8s provides tls-certificates" (while it requires/consumes it).

Can you please swipe it. Tnx!
P.S. I really like new `Integrations` tab. Nice!!!

**Comment by steverydz** [comment]
Hi @taurus-forever. This is now fixed and live.
