### ISSUE TITLE
Charmhub is parsing discourse post titles differently to ubuntu.com

### ISSUE THREAD

**Issue by grobbie** [canonical/charmhub.io#1568]
This leads to duplicated post titles on Ubuntu.com:

![image](https://user-images.githubusercontent.com/3254480/233116335-8a79498f-f5f9-494b-8cc6-6e385913a0cd.png)

![image](https://user-images.githubusercontent.com/3254480/233116410-95e5ecea-5abf-4fd4-8a13-e6f91ee2b0d5.png)

Please update the library charmhub is using, thanks

**Comment by Lukewh** [comment]
Hi @grobbie, can you provide a link to both pages?
It's not clear what the outcome here should be – on the one hand, you'd like Charmhub to be updated to be the same as ubuntu.com, but you say ubuntu.com is incorrect?

**Comment by Lukewh** [comment]
We'll take a look!
Can you provide links to:
- the page on Ubuntu.com
- the page on charmhub.io
- the Discourse post

Thanks :)

**Comment by grobbie** [comment]
https://ubuntu-com-12806.demos.haus/data/docs/mongodb-vm

https://charmhub.io/mongodb

https://discourse.charmhub.io/t/charmed-mongodb-docs/7663
