### ISSUE TITLE
500: This page isn’t working for `/topics/canonical-observability-stack/tutorials/instrumenting-machine-charms`

### ISSUE THREAD

**Issue by nobuto-m** [canonical/charmhub.io#1697]
The following page has a link to `/topics/canonical-observability-stack/tutorials/instrumenting-machine-charms` in the side bar.
https://charmhub.io/topics/canonical-observability-stack

However, the link returns `500: This page isn’t working`
https://charmhub.io/topics/canonical-observability-stack/tutorials/instrumenting-machine-charms

**Comment by Lukewh** [comment]
Seems like there was some strange cache state that has been cleared, thanks for the report!
