### ISSUE TITLE
Missing icons on recently promoted charms to non-latest/stable

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charmhub.io#1701]
Hi,

We have recently switched the list of charms to the stable risk but icons are missing on charmhub:
![Screenshot from 2023-10-29 18-15-06](https://github.com/canonical/charmhub.io/assets/1928266/2c1ad729-0eee-4f26-8e79-5d094c76d09c)

https://charmhub.io/mysql-router-k8s (the default track is `8.0` and `8.0/stable` has icon.svg)
https://charmhub.io/pgbouncer-k8s (the default track is `1` and `1/stable` has icon.svg)

Note: the default track there is NOT a `latest`.

Still, it used to work about a month ago for the same `icon.svg` in Git repo for those charms (with non-latest default track too):
https://charmhub.io/mysql
https://charmhub.io/mysql-k8s
https://charmhub.io/postgresql
https://charmhub.io/postgresql-k8s

Can you please hint us what could be the issue here? Tnx!

**Comment by Lukewh** [comment]
Hi @taurus-forever, the only insight I can provide is that if the Store API provides an icon, we show it on the website. It appears for these that the icon isn't being passed through to the web font end. I'll alert the store team to this issue and see if they can provide more feedback.

**Comment by verterok** [comment]
Hi @taurus-forever ,
I checked logs and the data for mysql-router-k8s and everything looks ok. As in the scan and release process worked, there is an icon in the metadata extracted from the package during the scan step, but it was not included in the release. 
The only case for that is when the status of the snap was not `published` at the time of the release....but I don't really know how that could be possible but I see the status is `published` now.
Could you try releasing the same revision of mysql-router-k8s again? 

Thanks

**Comment by taurus-forever** [comment]
@verterok thank you for the quick reply.
1) I have re-released `mysql-router-k8s` and the icon is properly shown now. \o/
I have re-released `pgbouncer-k8s` and the icon is still missing: https://charmhub.io/pgbouncer-k8s
```
15:27:47 ✔ taurus:~$ charmcraft release pgbouncer-k8s --channel 1/stable --revision 76 --resource pgbouncer-image:71
Revision 76 of 'pgbouncer-k8s' released to 1/stable (attaching resources: 'pgbouncer-image' r71)                                                                                    
15:28:11 ✔ taurus:~$ date
Mon Oct 30 03:29:24 PM EET 2023
```

2. I believe both charms were published long time ago. I do not recall changes here.
The recent changes are only: X/stable is released, default track switched to X and old latest track has been closed.
None are related, IMHO.

Any hints for `pgbouncer-k8s`? Tnx!

**Comment by verterok** [comment]
@taurus-forever Good to hear `mysql-router-k8s` is fixed, still will create a task on our side to add a bit more of instrumentation to get more data the next time this happens.
Regarding pgbouncer-k8s, the reason the icon (or any other metadata FWIW) is not updated is because track: `1` is not the default track and metadata (including icons) is only updated on a release to the default track (by default `latest`)

Cheers,

**Comment by taurus-forever** [comment]
The issue has gone after re-releasing the same revision to the default track.
Resolving the issue. Thank you!
