### ISSUE TITLE
'Charms in bundle' section a little broken on medium screens

### ISSUE THREAD

**Issue by petesfrench** [canonical/charmhub.io#1715]
Looks a little broken on medium screens:
![image](https://github.com/canonical/charmhub.io/assets/58276363/a916ec9a-57df-43a5-87d4-fc9db64927e1)
Changing the `col-medium-3` to a `col-medium-6` seems to fix it:
![image](https://github.com/canonical/charmhub.io/assets/58276363/f7376f9a-d438-4aeb-b509-ef309b9ce980)

**Comment by steverydz** [comment]
Thanks @petesfrench. This is now fixed.
