### ISSUE TITLE
pagination not reset when updating search

### ISSUE THREAD

**Issue by jw-can** [canonical/charmhub.io#1726]
When doing a search, the site sticks to the previously viewed result page number.
This can be confusing to users. Also it can result in a buggy behaviour, where no result page is active (because previous one is out of range) and a faulty message is displayed (e..g ```Showing 37 to 38 of 14 results for "logging".```)

Steps to reproduce:
1. display all charms
2. access result page 4
3. search for "logging"

Desired behaviour would be to always display result page 1 when doing a search.

**Comment by steverydz** [comment]
Thanks @jw-can. This is now fixed and in production.
